# Start with: tmuxinator local

name: git-odyssey
root: .
startup_window: app

windows:
  - app:
      panes:
        - docker compose up -d db && npm run desktop:dev
  - lazygit:
      panes:
        - lazygit
  - lazydocker:
      panes:
        - lazydocker
  - ghostty:
      panes:
        - clear
