services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    env_file:
      - src/.env
    command: ["python", "main.py"]
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    working_dir: /app/src
    restart: on-failure:5
