name: git-odyssey
channels:
  - conda-forge
dependencies:
  # Python interpreter and core packages
  - python=3.13.7
  - pip=25.2

  # Your primary Python dependencies
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pygit2=1.18.2
  - pygithub=2.1.1
  - langchain-core
  - langchain-openai
  - psycopg2
  - sqlalchemy
  - pgvector
  - pgvector-python
  - python-dotenv
  - fastapi
  - uvicorn

  # Necessary C-level dependencies (Versioned for stability)
  - libgit2=1.9.1
  - libssh2=1.11.1
  - openssl=3.5.3
  - cffi=2.0.0
  - libexpat=2.7.1
  - libffi=3.4.6

  # Other utilities (Keeping specific versions where defined)
  - annotated-types=0.7.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - pycparser=2.22
  - readline=8.2
  - tk=8.6.13
  - ncurses=6.5
  - bzip2=1.0.8
  - liblzma=5.8.1
  - libzlib=1.3.1
  - libsqlite=3.50.4
  - ca-certificates
  - icu
  - libiconv
  - libmpdec
  - pcre2
  - tzdata
